language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  pip install -r requirements.txt

script: python test_schemes.py

notifications:
  on_failure: always
  on_success: change
